package Task02;

import java.net.UnknownHostException;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.MongoClient;

public class InsertDriver {
	public static void main(String[] args) throws UnknownHostException {
		// connect to mongodb
		DB dB = (new MongoClient("localhost", 27017)).getDB("HuffPostTask02");
		DBCollection dBCollection = dB.getCollection("Channel");		
		// insert data here
		BasicDBObject basicDBObject0 = new BasicDBObject();
		basicDBObject0.put("SSN", "000-00-0000");
		basicDBObject0.put("name", "A");
		basicDBObject0.put("age", "20");
		basicDBObject0.put("gender", "M");
		basicDBObject0.put("department", "IT");
		dBCollection.insert(basicDBObject0);
		BasicDBObject basicDBObject1 = new BasicDBObject();
		basicDBObject1.put("SSN", "000-00-0001");
		basicDBObject1.put("name", "B");
		basicDBObject1.put("age", "21");
		basicDBObject1.put("gender", "M");
		basicDBObject1.put("department", "IT");
		dBCollection.insert(basicDBObject1);
		BasicDBObject basicDBObject2 = new BasicDBObject();
		basicDBObject2.put("SSN", "000-00-0002");
		basicDBObject2.put("name", "C");
		basicDBObject2.put("age", "22");
		basicDBObject2.put("gender", "M");
		basicDBObject2.put("department", "IT");
		dBCollection.insert(basicDBObject2);
		BasicDBObject basicDBObject3 = new BasicDBObject();
		basicDBObject3.put("SSN", "000-00-0003");
		basicDBObject3.put("name", "D");
		basicDBObject3.put("age", "21");
		basicDBObject3.put("gender", "M");
		basicDBObject3.put("department", "IT");
		dBCollection.insert(basicDBObject3);
		BasicDBObject basicDBObject4 = new BasicDBObject();
		basicDBObject4.put("SSN", "000-00-0004");
		basicDBObject4.put("name", "AA");
		basicDBObject4.put("age", "22");
		basicDBObject4.put("gender", "M");
		basicDBObject4.put("department", "IT");
		dBCollection.insert(basicDBObject4);
		BasicDBObject basicDBObject5 = new BasicDBObject();
		basicDBObject5.put("SSN", "000-00-0005");
		basicDBObject5.put("name", "AB");
		basicDBObject5.put("age", "19");
		basicDBObject5.put("gender", "F");
		basicDBObject5.put("department", "HR");
		dBCollection.insert(basicDBObject5);
		BasicDBObject basicDBObject6 = new BasicDBObject();
		basicDBObject6.put("SSN", "000-00-0006");
		basicDBObject6.put("name", "AC");
		basicDBObject6.put("age", "31");
		basicDBObject6.put("gender", "M");
		basicDBObject6.put("department", "HR");
		dBCollection.insert(basicDBObject6);
		BasicDBObject basicDBObject7 = new BasicDBObject();
		basicDBObject7.put("SSN", "000-00-0007");
		basicDBObject7.put("name", "AD");
		basicDBObject7.put("age", "18");
		basicDBObject7.put("gender", "F");
		basicDBObject7.put("department", "HR");
		dBCollection.insert(basicDBObject7);
		BasicDBObject basicDBObject8 = new BasicDBObject();
		basicDBObject8.put("SSN", "000-00-0008");
		basicDBObject8.put("name", "BA");
		basicDBObject8.put("age", "34");
		basicDBObject8.put("gender", "M");
		basicDBObject8.put("department", "HR");
		dBCollection.insert(basicDBObject8);
		BasicDBObject basicDBObject9 = new BasicDBObject();
		basicDBObject9.put("SSN", "000-00-0009");
		basicDBObject9.put("name", "BB");
		basicDBObject9.put("age", "31");
		basicDBObject9.put("gender", "M");
		basicDBObject9.put("department", "HR");
		dBCollection.insert(basicDBObject9);
		BasicDBObject basicDBObject10 = new BasicDBObject();
		basicDBObject10.put("SSN", "000-00-0010");
		basicDBObject10.put("name", "BC");
		basicDBObject10.put("age", "22");
		basicDBObject10.put("gender", "F");
		basicDBObject10.put("department", "Marketing");
		dBCollection.insert(basicDBObject10);
		BasicDBObject basicDBObject11 = new BasicDBObject();
		basicDBObject11.put("SSN", "000-00-0011");
		basicDBObject11.put("name", "BD");
		basicDBObject11.put("age", "41");
		basicDBObject11.put("gender", "F");
		basicDBObject11.put("department", "Marketing");
		dBCollection.insert(basicDBObject11);
		BasicDBObject basicDBObject12 = new BasicDBObject();
		basicDBObject12.put("SSN", "000-00-0012");
		basicDBObject12.put("name", "CA");
		basicDBObject12.put("age", "28");
		basicDBObject12.put("gender", "F");
		basicDBObject12.put("department", "Marketing");
		dBCollection.insert(basicDBObject12);
		BasicDBObject basicDBObject13 = new BasicDBObject();
		basicDBObject13.put("SSN", "000-00-0013");
		basicDBObject13.put("name", "CB");
		basicDBObject13.put("age", "31");
		basicDBObject13.put("gender", "M");
		basicDBObject13.put("department", "Marketing");
		dBCollection.insert(basicDBObject13);
		BasicDBObject basicDBObject14 = new BasicDBObject();
		basicDBObject14.put("SSN", "000-00-0014");
		basicDBObject14.put("name", "CC");
		basicDBObject14.put("age", "27");
		basicDBObject14.put("gender", "M");
		basicDBObject14.put("department", "Marketing");
		dBCollection.insert(basicDBObject14);
		BasicDBObject basicDBObject15 = new BasicDBObject();
		basicDBObject15.put("SSN", "000-00-0015");
		basicDBObject15.put("name", "CD");
		basicDBObject15.put("age", "26");
		basicDBObject15.put("gender", "M");
		basicDBObject15.put("department", "FINANCE");
		dBCollection.insert(basicDBObject15);
		BasicDBObject basicDBObject16 = new BasicDBObject();
		basicDBObject16.put("SSN", "000-00-0016");
		basicDBObject16.put("name", "DA");
		basicDBObject16.put("age", "26");
		basicDBObject16.put("gender", "M");
		basicDBObject16.put("department", "FINANCE");
		dBCollection.insert(basicDBObject16);
		BasicDBObject basicDBObject17 = new BasicDBObject();
		basicDBObject17.put("SSN", "000-00-0017");
		basicDBObject17.put("name", "DB");
		basicDBObject17.put("age", "21");
		basicDBObject17.put("gender", "M");
		basicDBObject17.put("department", "FINANCE");
		dBCollection.insert(basicDBObject17);
		BasicDBObject basicDBObject18 = new BasicDBObject();
		basicDBObject18.put("SSN", "000-00-0018");
		basicDBObject18.put("name", "DC");
		basicDBObject18.put("age", "22");
		basicDBObject18.put("gender", "M");
		basicDBObject18.put("department", "FINANCE");
		dBCollection.insert(basicDBObject18);
		BasicDBObject basicDBObject19 = new BasicDBObject();
		basicDBObject19.put("SSN", "000-00-0019");
		basicDBObject19.put("name", "DD");
		basicDBObject19.put("age", "23");
		basicDBObject19.put("gender", "M");
		basicDBObject19.put("department", "FINANCE");
		dBCollection.insert(basicDBObject19);
	}
}
